name: build_push_dev_image
on:
  workflow_dispatch

jobs:
  prepare-build:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.set_output.outputs.IMAGE_TAG }}
    steps:
      - name: Set IMAGE_TAG
        id: set_output
        run: |
          echo IMAGE_TAG=$(echo ${GITHUB_SHA}) >> $GITHUB_OUTPUT
          echo $(git describe --abbrev=0 --tags `git rev-list --tags --max-count=1`)
          echo $(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)
        
  build:
    needs: [prepare-build]
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ needs.prepare-build.outputs.IMAGE_TAG }}
    steps:
      - name: check
        run: echo $IMAGE_TAG
