name: Release Publish Workflow

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set env for release
        if: ${{ github.event_name == 'release' }}
        run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: Check RELEASE_VERSION format # valid example: 1.0.0 (release), 1.0.1-rc-202101010000 (workflow_dispatch)
        run: echo ${RELEASE_VERSION} | grep -cE '^[0-9]+.[0-9]+.[0-9]+(|-rc-[0-9]+)$'
      - name: test
        run: echo ${RELEASE_VERSION}
