name: Publish package to GitHub Packages
on:
  release:
    types: [released]

  workflow_dispatch:
    inputs:
      version:
        description: "version (format: '^[0-9]+.[0-9]+.[0-9]$') e.g. '1.0.21' (package name will be '<version>-rc-yyyyMMddHHmm')"
        required: true

jobs:
  prepare-publish:
    runs-on: ubuntu-latest
    outputs:
      SHOULD_PUBLISH: ${{ steps.should_publish.outputs.SHOULD_PUBLISH }}
    steps:
      - name: check branch for release
        if: ${{ github.event_name == 'release' && github.event.release.target_commitish != 'master'}}
        run: |
          echo "we need to use master branch for release."
          exit 1

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Get last two GITHUB tags to compare differences
        id: fetch_git_tags
        run: |
          LATEST_TAG=$(git describe --abbrev=0 --tags `git rev-list --tags --max-count=1`)
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_OUTPUT
          echo "Latest tag is ${LATEST_TAG}"
          PREV_TAG=$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)
          echo "PREV_TAG=${PREV_TAG}" >> $GITHUB_OUTPUT
          echo "Previous tag is ${PREV_TAG}"
      - name: Check GITHUB diff to confirm whether build should publish or not
        id: git_diff
        if: $${{steps.fetch_git_tags.outputs.PREV_TAG != steps.fetch_git_tags.outputs.LATEST_TAG}}
        run: |
          if git diff --name-only --exit-code ${{steps.fetch_git_tags.outputs.PREV_TAG}}  ${{steps.fetch_git_tags.outputs.LATEST_TAG}} -- src/main/proto; then
            echo "no need to publish proto jar since there is no difference!!"
            echo "SHOULD_PUBLISH=false" >> $GITHUB_OUTPUT
          else
            echo "will publish proto jar since there are some difference!!"
            echo "SHOULD_PUBLISH=true" >> $GITHUB_OUTPUT
          fi

  publish:
    needs: [prepare-publish]
    if: ${{needs.prepare-publish.outputs.SHOULD_PUBLISH == true}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
          cache: gradle

  send-release-announcement:
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
          cache: gradle
