name: Publish package to GitHub Packages
on:
  release:
    types: [released]

  workflow_dispatch:
    inputs:
      version:
        description: "version (format: '^[0-9]+.[0-9]+.[0-9]$') e.g. '1.0.21' (package name will be '<version>-rc-yyyyMMddHHmm')"
        required: true

jobs:
  prepare-publish:
    runs-on: ubuntu-latest
    outputs:
      SHOULD_PUBLISH: ${{ steps.should_publish.outputs.SHOULD_PUBLISH }}
    steps:
      - name: check branch for release
        if: ${{ github.event_name == 'release' && github.event.release.target_commitish != 'master'}}
        run: |
          echo "we need to use master branch for release."
          exit 1

      - uses: actions/checkout@v4

      - name: Get last two GITHUB tags to compare differences
        id: fetch_git_tags
        run: |
          git fetch --tags 
          LATEST_TAG=$(git describe --abbrev=0 --tags `git rev-list --tags --max-count=1`)
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_OUTPUT
          PREV_TAG=$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)
          echo "PREV_TAG=${PREV_TAG}" >> $GITHUB_OUTPUT>> $GITHUB_OUTPUT
      - name: GET GITHUB differences for proto files
        id: git_diff
        if: $${{ steps.fetch_git_tags.outputs.PREV_TAG != steps.fetch_git_tags.outputs.LATEST_TAG }}
        run: |
            PROTO_GIT_DIFF=$(git diff --name-only  ${{steps.fetch_git_tags.outputs.PREV_TAG}}  ${{steps.fetch_git_tags.outputs.LATEST_TAG}} -- src/main/proto)
            echo "proto git diff is:$PROTO_GIT_DIFF:"
            echo "PROTO_GIT_DIFF=${PROTO_GIT_DIFF}" >> $GITHUB_OUTPUT
      - name: Check whether build should publish or not
        id: should_publish
        if: $${{ steps.fetch_git_tags.outputs.PREV_TAG != steps.fetch_git_tags.outputs.LATEST_TAG }}
        run: |
          if [ -z "$steps.git_diff.outputs.PROTO_GIT_DIFF" ]; then
            echo "no need to publish proto jar since there is no difference!!"
            echo "SHOULD_PUBLISH=false" >> $GITHUB_OUTPUT
          fi

  publish:
    needs: [prepare-publish]
    if: ${{needs.prepare-publish.outputs.SHOULD_PUBLISH}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
          cache: gradle


  send-release-announcement:
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - name: Set env for release
        run: echo "RELEASE_VERSION"
