name: build_push_dev_image
on:
  workflow_dispatch:

env:
  ECR_REPO_PATH: dev/import-processor

jobs:
  prepare-build:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.set_output.outputs.IMAGE_TAG }}
    steps:
      - name: Set IMAGE_TAG
        id: set_output
        run: echo ::set-output name=IMAGE_TAG::$(echo ${GITHUB_SHA})

  build:
    needs: [prepare-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BEBIT_MACHINE_GITHUB_TOKEN }}
          fetch-depth: 0
          submodules: recursive
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: ${{ env.ECR_REPO_PATH }}
          tags: ${{ needs.prepare-build.outputs.IMAGE_TAG }}
          registry: ${{ secrets.CONTAINER_REGISTRY_PATH }}
          dockerfile: processor/Dockerfile
          buildArgs: GITHUB_ACTOR=bebit-machine,GITHUB_TOKEN=${{ secrets.BEBIT_MACHINE_GITHUB_TOKEN }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
